# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ankurdivekar.github.io',
                'doc_host': 'https://ankurdivekar.github.io',
                'git_url': 'https://github.com/ankurdivekar/ankurdivekar.github.io',
                'lib_path': 'ankurdivekar.github.io'},
  'syms': {'ankurdivekar.github.io.core': {'ankurdivekar.github.io.core.foo': ('core.html#foo', 'ankurdivekar.github.io/core.py')}}}
